app = "gtmb"
build = { }
primary_region = "lax"

[http_service]
auto_start_machines = false
auto_stop_machines = false
force_https = true
internal_port = 8_080
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
