name: Update URL

on:
  push:
    paths:
      - '**/*'

jobs:
  update_url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Call URL
        run: |
          curl -X GET https://github.com/codespaces/automatic-disco-wp9vgwrjpqh9pwv \
          -u thanhtayt:11042006Ff@
