name: auto-start-codespaces

on:
  push:

jobs:
  start-codespaces:
    runs-on: ubuntu

    steps:
      - uses: actions/checkout@v2

      - name: Start Codespaces
        uses: google/codespaces@v1
        with:
          action: start-codespaces

