name: Keep Codespace Running

on:
  push:
    branches:
      - main

jobs:
  keep_running:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node.js and dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          
      - name: Install @octokit/rest
        run: npm install @octokit/rest
      
      - name: Keep Codespace Running
        run: |
          const { Octokit } = require("@octokit/rest");

          const octokit = new Octokit({
            auth: process.env.MY_OTHER_TOKEN,
          });

          const response = await octokit.codespaces.getSuspended({ owner: 'thanhtayt', repo: 'Gemini-Telegram-Bot' });
          if (response.data.length > 0) {
            await octokit.codespaces.unsuspend({ owner: 'thanhtayt', repo: 'Gemini-Telegram-Bot' });
          }
