name: Restart Codespace on File Update

on:
  push:
    paths:
      - '**' # Chạy khi có thay đổi trên bất kỳ file nào trong repository

jobs:
  restart-codespace:
    runs-on: ubuntu-latest

    steps:
    - name: Get Codespace Name
      id: get_codespace_name
      run: |
        CODESPACE_URL="https://automatic-disco-wp9vgwrjpqh9pwv.github.dev/"
        CODESPACE_NAME=$(basename "$CODESPACE_URL")
        echo "::set-output name=codespace_name::$CODESPACE_NAME"

    - name: Restart Codespace
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Chỉ chạy khi push vào nhánh main
      run: |
        CODESPACE_NAME="${{ steps.get_codespace_name.outputs.codespace_name }}"
        CODESPACE_ID=$(curl -sL -H "Authorization: token ${{ secrets.my_custom_pat }}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/user/codespaces" | jq -r --arg CODESPACE_NAME "$CODESPACE_NAME" '.codespaces[] | select(.name == $CODESPACE_NAME) | .id')
        if [ -n "$CODESPACE_ID" ]; then
          curl -X POST \
            -H "Authorization: token ${{ secrets.my_custom_pat }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"force_restart": true}' \
            "https://api.github.com/codespaces/$CODESPACE_ID/restart"
        else
          echo "Không tìm thấy Codespace với tên '$CODESPACE_NAME'"
        fi
