name: Start Codespace on File Update

on:
  push:
    paths:
      - '**' # Sẽ chạy khi có thay đổi trên bất kỳ file nào trong repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start Codespace
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Chỉ chạy khi push vào branch main
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.my_custom_pat }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"name": "automatic disco"}' \
          https://api.github.com/repos/thanhtayt/Gemini-Telegram-Bot/codespaces
