name: Start Codespaces on File Update

on:
  push:
    paths:
      - '**' # Chạy khi có thay đổi trên bất kỳ file nào trong repository

jobs:
  start-codespaces:
    runs-on: windows-latest

    steps:
    - name: Start Codespace
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Chỉ chạy khi push vào nhánh main
      run: |
        CODESPACES_URL="https://github.com/codespaces/automatic-disco-wp9vgwrjpqh9pwv?editor=web"
        curl -X POST \
          -H "Authorization: token ${{ secrets.my_custom_pat }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "$CODESPACES_URL"
