name: Start Codespace on File Update
on:
  push:
    paths:
      - '**/*'

jobs:
  start-codespace:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start Codespace
      run: |
        # Here goes the script to start Codespace using GitHub REST API
        # Example:
        # curl -X POST \
        #   -H "Authorization: token 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" \
        #   -H "Accept: application/vnd.github.v3+json" \
        #   -d '{"ref":"main","repository":"Gemini-Telegram-Bot"}' \
        #   https://api.github.com/repos/thanhtayt/Gemini-Telegram-Bot/actions/workflows/your_workflow_name/dispatches
