name: Start Codespace on File Update

on:
  push:
    paths:
      - '**/*'

jobs:
  start-codespace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start Codespace
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.my_custom_pat }}
          script: |
            const { data: codespaces } = await github.request('GET /user/codespaces')
            if (codespaces.length === 0) {
              await github.request('POST /user/codespaces')
            } else {
              console.log('Codespace already exists.')
            }
