name: Keep Codespace Running

on:
  push:
    branches:
      - main

jobs:
  keep_running:
    runs-on: ubuntu-latest

    steps:
      - name: Install @octokit/rest
        run: npm install @octokit/rest
      
      - name: Keep Codespace Running
        uses: actions/github-script@v5
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            const octokit = new Octokit({
              auth: process.env.MY_OTHER_TOKEN,
            });
            try {
              const response = await octokit.codespaces.listForAuthenticatedUser();
              if (response.data.length > 0) {
                // Codespace is running
                console.log("Codespace is running");
              } else {
                // Codespace is suspended
                console.log("Codespace is suspended");
                // Uncomment the following line to unsuspend the Codespace
                // await octokit.request('POST /codespaces/{codespace_id}/unsuspend', { codespace_id: 'YOUR_CODESPACE_ID' });
              }
            } catch (error) {
              console.error("Error:", error.message);
              process.exit(1);
            }
