name: Keep Codespace Running

on:
  push:
    branches:
      - main

jobs:
  keep_running:
    runs-on: ubuntu-latest

    steps:
      - name: Install @octokit/rest
        run: npm install @octokit/rest
      
      - name: Keep Codespace Running
        uses: actions/github-script@v5
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            const octokit = new Octokit({
              auth: process.env.MY_OTHER_TOKEN,
            });
            try {
              const response = await octokit.codespaces.getSuspended({ owner: 'thanhtayt', repo: 'Gemini-Telegram-Bot' });
              if (response.data.length > 0) {
                await octokit.codespaces.unsuspend({ owner: 'thanhtayt', repo: 'Gemini-Telegram-Bot' });
              }
            } catch (error) {
              console.error("Error:", error.message);
              process.exit(1);
            }
