name: Create and Maintain Codespace

on:
  push:
    branches:
      - main

jobs:
  create-and-maintain-codespace:
    runs-on: ubuntu-latest

    steps:
      - name: Create Codespace
        uses: actions/github-script@v5
        with:
          script: |
            const response = await github.request('POST /repos/{owner}/{repo}/codespaces', {
              owner: 'thanhayt',
              repo: 'Gemini-Telegram-Bot',
              headers: {
                Authorization: `token ${{ secrets.my_custom_pat }}`,
                Accept: 'application/vnd.github.v3+json'
              },
              data: {
                name: 'automatic-disco',
                instance_type: 'standard'
              }
            });
            console.log(response);

      - name: Keep Codespace Alive
        run: |
          while true; do
            sleep 600  # Keep the workflow running for every 10 minutes
            echo "Codespace is still running..."
          done
