name: Run Codespace on File Update

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start Codespace
      uses: codespaces-examples/start-codespace@v1
      with:
        codespace_name: automatic-disco
        github_token: ${{ secrets.my_custom_pat }}
